# -*- coding: utf-8 -*-
"""Метод HIVES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxvGD_LMNqc3S2utI5447ZkovQnIAmvD

Подключение через гит хаб
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Karperash/Metod-HIVES.git
# %cd Metod-HIVES

!pip -q install numpy

!python main.py input.json